version: "3.7"

services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass Redis123!
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:
